package com.imall.common.domain;

import java.sql.Timestamp;

import org.apache.commons.lang.StringUtils;

import com.imall.common.domain.BasicDomain;
import com.imall.common.utils.CommonConstants;

public class XMPPUser extends BasicDomain{
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 8362417916615830495L;
	
    protected String chatId;//对应的xmpp server的jid
    protected String chatNickName;
    protected String chatPassword;
    protected Integer newMessageNumber;
    protected String latestMessage;
    protected Timestamp latestMessageTime;
    protected Long latestMessageUserId;
    
    protected boolean isOwner = false;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_chat_info.chat_id
     *
     * @return the value of u_user_chat_info.chat_id
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public String getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_chat_info.chat_id
     *
     * @param chatId the value for u_user_chat_info.chat_id
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public void setChatId(String chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_chat_info.chat_password
     *
     * @return the value of u_user_chat_info.chat_password
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public String getChatPassword() {
        return chatPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_chat_info.chat_password
     *
     * @param chatPassword the value for u_user_chat_info.chat_password
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public void setChatPassword(String chatPassword) {
        this.chatPassword = chatPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_chat_info.new_message_number
     *
     * @return the value of u_user_chat_info.new_message_number
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public Integer getNewMessageNumber() {
        return newMessageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_chat_info.new_message_number
     *
     * @param newMessageNumber the value for u_user_chat_info.new_message_number
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public void setNewMessageNumber(Integer newMessageNumber) {
        this.newMessageNumber = newMessageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_chat_info.latest_message
     *
     * @return the value of u_user_chat_info.latest_message
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public String getLatestMessage() {
        return latestMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_chat_info.latest_message
     *
     * @param latestMessage the value for u_user_chat_info.latest_message
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public void setLatestMessage(String latestMessage) {
        this.latestMessage = latestMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_chat_info.latest_message_time
     *
     * @return the value of u_user_chat_info.latest_message_time
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public Timestamp getLatestMessageTime() {
        return latestMessageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_chat_info.latest_message_time
     *
     * @param latestMessageTime the value for u_user_chat_info.latest_message_time
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public void setLatestMessageTime(Timestamp latestMessageTime) {
        this.latestMessageTime = latestMessageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_chat_info.latest_message_user_id
     *
     * @return the value of u_user_chat_info.latest_message_user_id
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public Long getLatestMessageUserId() {
        return latestMessageUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_chat_info.latest_message_user_id
     *
     * @param latestMessageUserId the value for u_user_chat_info.latest_message_user_id
     *
     * @mbggenerated Mon May 16 13:29:32 CST 2016
     */
    public void setLatestMessageUserId(Long latestMessageUserId) {
        this.latestMessageUserId = latestMessageUserId;
    }

	public String getChatNickName() {
		if(StringUtils.isBlank(chatNickName)){
			return this.getChatId();
		}
		return chatNickName;
	}

	public void setChatNickName(String chatNickName) {
		this.chatNickName = chatNickName;
	}

	public boolean isOwner() {
		return isOwner;
	}

	public void setOwner(boolean isOwner) {
		this.isOwner = isOwner;
	}
	
	public String getJid(){
		if(StringUtils.isBlank(this.getChatId())){
			return null;
		}
		return this.getChatId() + "@" + CommonConstants.XMPP_USER_SERVICE_NAME;
	}
}