package com.imall.common.utils;

import java.util.*;

public class DeviceConstants {

	public static final String DEVICE_MODEL_NAME_IPHONEX = "iPhone X";

	public static final String BRAND_NAME_SAMSUNG = "samsung";
	public static final String BRAND_NAME_VIVO = "vivo";
	public static final String BRAND_NAME_OPPO = "OPPO";
	public static final String BRAND_NAME_HUAWEI = "huawei";
	public static final String BRAND_NAME_XIAOMI = "Xiaomi";
	public static final String BRAND_NAME_MEIZU = "meizu";
	public static final String BRAND_NAME_LENOVO = "lenovo";
	public static final String BRAND_NAME_LG = "LG";
	public static final String BRAND_NAME_COOLPAD = "coolpad";
	public static final String BRAND_NAME_ZTE = "ZTE";
	public static final String BRAND_NAME_TCL = "TCL";
	public static final String BRAND_NAME_ASUS = "ASUS";
	public static final String BRAND_NAME_LESHI = "leshi";
	public static final String BRAND_NAME_YIJIA = "yijia";
	public static final String BRAND_NAME_CHUIZI = "chuizi";
	
	public static final Map<String, Integer> BRAND_MARKET_SHARE = new LinkedHashMap<String, Integer>();
	
	public static final Map<String, List<AndroidDevice>> BRAND_DEVICES = new LinkedHashMap<String, List<AndroidDevice>>();
	
	public static final Map<String, Integer> ANDROID_VERSIONS = new LinkedHashMap<String, Integer>();
	
	public static final List<String> APP_PACKAGE_NAMES = new ArrayList<String>();
	
	static{
		BRAND_MARKET_SHARE.put(BRAND_NAME_SAMSUNG, 200);
		BRAND_MARKET_SHARE.put(BRAND_NAME_VIVO, 150);
		BRAND_MARKET_SHARE.put(BRAND_NAME_OPPO, 150);
		BRAND_MARKET_SHARE.put(BRAND_NAME_HUAWEI, 120);
		BRAND_MARKET_SHARE.put(BRAND_NAME_XIAOMI, 150);
		BRAND_MARKET_SHARE.put(BRAND_NAME_MEIZU, 30);
		BRAND_MARKET_SHARE.put(BRAND_NAME_LENOVO, 20);
		BRAND_MARKET_SHARE.put(BRAND_NAME_LG, 20);
		BRAND_MARKET_SHARE.put(BRAND_NAME_COOLPAD, 15);
		BRAND_MARKET_SHARE.put(BRAND_NAME_ZTE, 10);
		BRAND_MARKET_SHARE.put(BRAND_NAME_TCL, 12);
		BRAND_MARKET_SHARE.put(BRAND_NAME_ASUS, 10);
		BRAND_MARKET_SHARE.put(BRAND_NAME_LESHI, 4);
		BRAND_MARKET_SHARE.put(BRAND_NAME_YIJIA, 5);
		BRAND_MARKET_SHARE.put(BRAND_NAME_CHUIZI, 3);
		
		List<AndroidDevice> androidDevices = new ArrayList<AndroidDevice>();
		AndroidDevice device = new AndroidDevice(BRAND_NAME_SAMSUNG, "S5");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_SAMSUNG, "S6");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_SAMSUNG, "S7");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_SAMSUNG, "C5");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_SAMSUNG, "C6");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_SAMSUNG, "C7");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_SAMSUNG, "A9");
		androidDevices.add(device);
		BRAND_DEVICES.put(BRAND_NAME_SAMSUNG, androidDevices);
		
		androidDevices = new ArrayList<AndroidDevice>();
		device = new AndroidDevice(BRAND_NAME_VIVO, "X6");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_VIVO, "X6L");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_VIVO, "X6S");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_VIVO, "Xplay5");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_VIVO, "Xplay5L");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_VIVO, "V3");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_VIVO, "V3Max");
		androidDevices.add(device);
		BRAND_DEVICES.put(BRAND_NAME_VIVO, androidDevices);
		
		androidDevices = new ArrayList<AndroidDevice>();
		device = new AndroidDevice(BRAND_NAME_OPPO, "R7Plus");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "OPPOR7sm");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "OPPOR7sm");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R7Plusm");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "U707T");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R8207");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "N5207");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "OPPOR7s");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R7c");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R7007");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R819T");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R8107");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "1107");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "OPPOR9m");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R8007");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "OPPOR7");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "N5209");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "N1T");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "A31");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "X9007");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "OPPOA33m");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "OPPOA53m");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "A51");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "6607");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "A11");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R831S");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "OPPOR7sPlus");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R831T");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R7Plusm");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "X9077");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "A31t");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R8207");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "OPPOR7");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R7005");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "R8200");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_OPPO, "N5117");
		BRAND_DEVICES.put(BRAND_NAME_OPPO, androidDevices);
		
		androidDevices = new ArrayList<AndroidDevice>();
		device = new AndroidDevice(BRAND_NAME_HUAWEI, "P9");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_HUAWEI, "P8");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_HUAWEI, "P7");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_HUAWEI, "Mate8");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_HUAWEI, "Mate7");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_HUAWEI, "G9");
		androidDevices.add(device);
		BRAND_DEVICES.put(BRAND_NAME_HUAWEI, androidDevices);
		
		androidDevices = new ArrayList<AndroidDevice>();
		device = new AndroidDevice(BRAND_NAME_XIAOMI, "MI 5");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_XIAOMI, "MI 4S");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_XIAOMI, "MI 4");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_XIAOMI, "MI 4C");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_XIAOMI, "MI Note");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_XIAOMI, "MI Max");
		androidDevices.add(device);
		BRAND_DEVICES.put(BRAND_NAME_XIAOMI, androidDevices);
		
		androidDevices = new ArrayList<AndroidDevice>();
		device = new AndroidDevice(BRAND_NAME_MEIZU, "Note3");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_MEIZU, "MX5");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_MEIZU, "Pro6");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_MEIZU, "Pro5");
		androidDevices.add(device);
		device = new AndroidDevice(BRAND_NAME_MEIZU, "Note");
		androidDevices.add(device);
		BRAND_DEVICES.put(BRAND_NAME_MEIZU, androidDevices);


		ANDROID_VERSIONS.put("4.0.1", 14);
		ANDROID_VERSIONS.put("4.0.2", 14);
		ANDROID_VERSIONS.put("4.0.3", 15);
		ANDROID_VERSIONS.put("4.0.4", 15);
		ANDROID_VERSIONS.put("4.1.1", 16);
		ANDROID_VERSIONS.put("4.1.2", 16);
		ANDROID_VERSIONS.put("4.2.1", 17);
		ANDROID_VERSIONS.put("4.2.2", 17);
		ANDROID_VERSIONS.put("4.3.1", 18);
		ANDROID_VERSIONS.put("4.4.1", 19);
		ANDROID_VERSIONS.put("4.4.2", 19);
		ANDROID_VERSIONS.put("4.4.3", 19);
		ANDROID_VERSIONS.put("4.4.4", 19);
		ANDROID_VERSIONS.put("5.0.1", 21);
		ANDROID_VERSIONS.put("5.0.2", 21);
		ANDROID_VERSIONS.put("5.1.1", 22);
		ANDROID_VERSIONS.put("6.0.0", 23);
		ANDROID_VERSIONS.put("6.0.1", 23);
		ANDROID_VERSIONS.put("7.0.0", 24);

		
		APP_PACKAGE_NAMES.add("com.mediatek.gba");
		APP_PACKAGE_NAMES.add("com.yysc.one.vs");
		APP_PACKAGE_NAMES.add("com.vivo.weather.provider");
		APP_PACKAGE_NAMES.add("com.bbk.logservice");
		APP_PACKAGE_NAMES.add("com.android.providers.telephony");
		APP_PACKAGE_NAMES.add("com.vivo.smartmultiwindow");
		APP_PACKAGE_NAMES.add("com.android.providers.calendar");
		APP_PACKAGE_NAMES.add("com.bbk.scene.launcher.theme");
		APP_PACKAGE_NAMES.add("com.android.providers.media");
		APP_PACKAGE_NAMES.add("com.vivo.livewallpaper.coffeetime");
		APP_PACKAGE_NAMES.add("com.vivo.setupwizard");
		APP_PACKAGE_NAMES.add("com.qiyi.video");
		APP_PACKAGE_NAMES.add("com.mediatek.fwk.plugin");
		APP_PACKAGE_NAMES.add("com.mobiletools.systemhelper");
		APP_PACKAGE_NAMES.add("com.vivo.easyshare");
		APP_PACKAGE_NAMES.add("com.aspire.mm");
		APP_PACKAGE_NAMES.add("com.vivo.abe");
		APP_PACKAGE_NAMES.add("com.android.wallpapercropper");
		APP_PACKAGE_NAMES.add("com.mediatek.schpwronoff");
		APP_PACKAGE_NAMES.add("com.monitor");
		APP_PACKAGE_NAMES.add("com.sankuai.meituan");
		APP_PACKAGE_NAMES.add("com.youku.phone");
		APP_PACKAGE_NAMES.add("com.vivo.collage");
		APP_PACKAGE_NAMES.add("com.vivo.compass");
		APP_PACKAGE_NAMES.add("org.simalliance.openmobileapi.service");
		APP_PACKAGE_NAMES.add("com.huawei.appmarket");
		APP_PACKAGE_NAMES.add("com.vivo.mediatune");
		APP_PACKAGE_NAMES.add("com.android.documentsui");
		APP_PACKAGE_NAMES.add("com.android.galaxy4");
		APP_PACKAGE_NAMES.add("com.vivo.smartwakecustomgesture");
		APP_PACKAGE_NAMES.add("com.android.externalstorage");
		APP_PACKAGE_NAMES.add("com.mediatek.ygps");
		APP_PACKAGE_NAMES.add("com.android.htmlviewer");
		APP_PACKAGE_NAMES.add("com.vivo.cameraparamluma");
		APP_PACKAGE_NAMES.add("com.iflytek.speechsuite");
		APP_PACKAGE_NAMES.add("com.tencent.androidqqmail");
		APP_PACKAGE_NAMES.add("com.android.mms.service");
		APP_PACKAGE_NAMES.add("com.android.providers.downloads");
		APP_PACKAGE_NAMES.add("com.dianping.v1");
		APP_PACKAGE_NAMES.add("com.fw.upgrade");
		APP_PACKAGE_NAMES.add("com.vivo.simpleweather");
		APP_PACKAGE_NAMES.add("com.mediatek.engineermode");
		APP_PACKAGE_NAMES.add("com.vivo.weather");
		APP_PACKAGE_NAMES.add("com.android.bbkmusic");
		APP_PACKAGE_NAMES.add("com.bbk.VoiceOneshot");
		APP_PACKAGE_NAMES.add("com.mediatek.omacp");
		APP_PACKAGE_NAMES.add("com.bbk.ftplog");
		APP_PACKAGE_NAMES.add("com.vivo.msgpush");
		APP_PACKAGE_NAMES.add("com.android.browser");
		APP_PACKAGE_NAMES.add("com.mediatek.bluetoothle");
		APP_PACKAGE_NAMES.add("com.bbk.updater");
		APP_PACKAGE_NAMES.add("com.android.bbkcalculator");
		APP_PACKAGE_NAMES.add("com.laba.wcs");
		APP_PACKAGE_NAMES.add("com.vivo.ewarranty");
		APP_PACKAGE_NAMES.add("cc.fotoplace.app");
		APP_PACKAGE_NAMES.add("com.android.defcontainer");
		APP_PACKAGE_NAMES.add("com.android.pacprocessor");
		APP_PACKAGE_NAMES.add("com.android.filemanager");
		APP_PACKAGE_NAMES.add("com.vivo.bspservice");
		APP_PACKAGE_NAMES.add("com.guokr.fanta");
		APP_PACKAGE_NAMES.add("com.tencent.mm");
		APP_PACKAGE_NAMES.add("com.sankuai.meituan.takeoutnew");
		APP_PACKAGE_NAMES.add("com.vivo.securedaemonservice");
		APP_PACKAGE_NAMES.add("com.android.certinstaller");
		APP_PACKAGE_NAMES.add("com.vivo.smartshot");
		APP_PACKAGE_NAMES.add("android");
		APP_PACKAGE_NAMES.add("com.tencent.android.qqdownloader");
		APP_PACKAGE_NAMES.add("com.mediatek.connectivity");
		APP_PACKAGE_NAMES.add("com.android.contacts");
		APP_PACKAGE_NAMES.add("com.evangelium365pro.android");
		APP_PACKAGE_NAMES.add("com.vivo.upnpserver");
		APP_PACKAGE_NAMES.add("com.baidu.searchbox");
		APP_PACKAGE_NAMES.add("com.bbk.cloud");
		APP_PACKAGE_NAMES.add("com.bbk.VoiceAssistant");
		APP_PACKAGE_NAMES.add("com.bbk.theme");
		APP_PACKAGE_NAMES.add("com.mediatek.ftprecheck");
		APP_PACKAGE_NAMES.add("com.android.mms");
		APP_PACKAGE_NAMES.add("com.android.stk");
		APP_PACKAGE_NAMES.add("com.android.backupconfirm");
		APP_PACKAGE_NAMES.add("com.shuame.rootgenius");
		APP_PACKAGE_NAMES.add("com.tencent.assistant.yingyongbao_market_651");
		APP_PACKAGE_NAMES.add("com.bbk.calendar");
		APP_PACKAGE_NAMES.add("com.bbk.iqoo.feedback");
		APP_PACKAGE_NAMES.add("com.android.BBKClock");
		APP_PACKAGE_NAMES.add("com.letv.android.client");
		APP_PACKAGE_NAMES.add("com.android.BBKTools");
		APP_PACKAGE_NAMES.add("com.android.photoeditor");
		APP_PACKAGE_NAMES.add("com.android.wifisettings");
		APP_PACKAGE_NAMES.add("com.vivo.video.editor");
		APP_PACKAGE_NAMES.add("com.vlife.vivo.wallpaper");
		APP_PACKAGE_NAMES.add("com.mediatek.FMRadio");
		APP_PACKAGE_NAMES.add("com.vivo.daemonService");
		APP_PACKAGE_NAMES.add("com.android.contacts.contactsstaredwidget");
		APP_PACKAGE_NAMES.add("com.android.phasebeam");
		APP_PACKAGE_NAMES.add("com.mediatek.providers.drm");
		APP_PACKAGE_NAMES.add("com.ringclip");
		APP_PACKAGE_NAMES.add("com.iqoo.engineermode");
		APP_PACKAGE_NAMES.add("com.android.BBKPhoneInstructions");
		APP_PACKAGE_NAMES.add("com.android.providers.settings");
		APP_PACKAGE_NAMES.add("com.android.sharedstoragebackup");
		APP_PACKAGE_NAMES.add("com.parizene.netmonitor");
		APP_PACKAGE_NAMES.add("com.android.printspooler");
		APP_PACKAGE_NAMES.add("com.vivo.dream.note");
		APP_PACKAGE_NAMES.add("com.vivo.Tips");
		APP_PACKAGE_NAMES.add("com.vivo.game");
		APP_PACKAGE_NAMES.add("com.android.incallui");
		APP_PACKAGE_NAMES.add("com.tencent.qqlive");
		APP_PACKAGE_NAMES.add("com.baidu.appsearch");
		APP_PACKAGE_NAMES.add("com.android.webview");
		APP_PACKAGE_NAMES.add("com.android.inputdevices");
		APP_PACKAGE_NAMES.add("com.android.bluetoothsettings");
		APP_PACKAGE_NAMES.add("com.baidu.input_bbk.service");
		APP_PACKAGE_NAMES.add("com.bbk.photoframewidget");
		APP_PACKAGE_NAMES.add("com.estrongs.android.pop");
		APP_PACKAGE_NAMES.add("cmccwm.mobilemusic");
		APP_PACKAGE_NAMES.add("com.blinnnk.zeus");
		APP_PACKAGE_NAMES.add("com.android.vivo.mtklog");
		APP_PACKAGE_NAMES.add("com.getfun17.getfun");
		APP_PACKAGE_NAMES.add("com.android.skin");
		APP_PACKAGE_NAMES.add("com.mediatek");
		APP_PACKAGE_NAMES.add("com.cutt.zhiyue.android.app712574");
		APP_PACKAGE_NAMES.add("com.example");
		APP_PACKAGE_NAMES.add("com.whty.wicity.china");
		APP_PACKAGE_NAMES.add("com.ibimuyu.lockscreen");
		APP_PACKAGE_NAMES.add("com.bbk.iqoo.logsystem");
		APP_PACKAGE_NAMES.add("cn.emagsoftware.gamehall");
		APP_PACKAGE_NAMES.add("com.vivo.pctools.helper");
		APP_PACKAGE_NAMES.add("com.bbk.facewake");
		APP_PACKAGE_NAMES.add("com.mediatek.nlpservice");
		APP_PACKAGE_NAMES.add("com.ss.android.article.news");
		APP_PACKAGE_NAMES.add("com.android.server.telecom");
		APP_PACKAGE_NAMES.add("com.google.android.syncadapters.contacts");
		APP_PACKAGE_NAMES.add("com.android.keychain");
		APP_PACKAGE_NAMES.add("com.android.camera");
		APP_PACKAGE_NAMES.add("com.bbk.launcher2");
		APP_PACKAGE_NAMES.add("com.android.dialer");
		APP_PACKAGE_NAMES.add("com.dell.stage.widget.social");
		APP_PACKAGE_NAMES.add("com.google.android.gsf");
		APP_PACKAGE_NAMES.add("net.jaqpot.netcounter");
		APP_PACKAGE_NAMES.add("com.heymiao.miao");
		APP_PACKAGE_NAMES.add("com.tencent.mobileqq");
		APP_PACKAGE_NAMES.add("com.vivo.magic.note");
		APP_PACKAGE_NAMES.add("com.android.packageinstaller");
		APP_PACKAGE_NAMES.add("com.svox.pico");
		APP_PACKAGE_NAMES.add("com.vivo.networkstate");
		APP_PACKAGE_NAMES.add("net.mitu.app");
		APP_PACKAGE_NAMES.add("com.vivo.livewallpaper.silk");
		APP_PACKAGE_NAMES.add("com.android.proxyhandler");
		APP_PACKAGE_NAMES.add("cn.cmvideo.isj");
		APP_PACKAGE_NAMES.add("com.android.VideoPlayer");
		APP_PACKAGE_NAMES.add("com.android.BBKCrontab");
		APP_PACKAGE_NAMES.add("com.android.musiceffecttest");
		APP_PACKAGE_NAMES.add("com.wandoujia.phoenix2");
		APP_PACKAGE_NAMES.add("com.xiaomi.market");
		APP_PACKAGE_NAMES.add("com.google.android.syncadapters.calendar");
		APP_PACKAGE_NAMES.add("com.iqoo.secure");
		APP_PACKAGE_NAMES.add("com.mediatek.atci.service");
		APP_PACKAGE_NAMES.add("com.mediatek.thermalmanager");
		APP_PACKAGE_NAMES.add("com.iqoo.powersaving");
		APP_PACKAGE_NAMES.add("com.vivo.magic.clockweathermusic");
		APP_PACKAGE_NAMES.add("com.android.skintwo");
		APP_PACKAGE_NAMES.add("com.android.noisefield");
		APP_PACKAGE_NAMES.add("com.vivo.flashlightservice");
		APP_PACKAGE_NAMES.add("com.bbk.appstore");
		APP_PACKAGE_NAMES.add("com.google.android.gsf.login");
		APP_PACKAGE_NAMES.add("com.mtk.telephony");
		APP_PACKAGE_NAMES.add("com.vivo.fingerprint.fpc.service");
		APP_PACKAGE_NAMES.add("com.oppo.market");
		APP_PACKAGE_NAMES.add("com.vivo.findphone");
		APP_PACKAGE_NAMES.add("com.yunzo.cs");
		APP_PACKAGE_NAMES.add("com.mediatek.smartmotion");
		APP_PACKAGE_NAMES.add("cn.cj.pe");
		APP_PACKAGE_NAMES.add("com.qihoo.appstore");
		APP_PACKAGE_NAMES.add("com.android.bbk.lockscreen3");
		APP_PACKAGE_NAMES.add("com.vivo.audiofx");
		APP_PACKAGE_NAMES.add("com.autonavi.cmccmap");
		APP_PACKAGE_NAMES.add("com.tencent.news");
		APP_PACKAGE_NAMES.add("com.vivo.dream.weather");
		APP_PACKAGE_NAMES.add("com.bbk.theme.resources");
		APP_PACKAGE_NAMES.add("com.android.settings");
		APP_PACKAGE_NAMES.add("com.fw.upgrade.sysoper");
		APP_PACKAGE_NAMES.add("com.autonavi.minimap");
		APP_PACKAGE_NAMES.add("com.mediatek.lbs.em2.ui");
		APP_PACKAGE_NAMES.add("fi.iltasanomat");
		APP_PACKAGE_NAMES.add("com.ustclin.ai");
		APP_PACKAGE_NAMES.add("jp.mang.appli");
		APP_PACKAGE_NAMES.add("com.mappn.gfan");
		APP_PACKAGE_NAMES.add("com.iflytek.inputmethod");
		APP_PACKAGE_NAMES.add("com.bbk.scene.databaseprovider");
		APP_PACKAGE_NAMES.add("com.vivo.dream.clock");
		APP_PACKAGE_NAMES.add("com.vivo.dream.music");
		APP_PACKAGE_NAMES.add("com.android.wallpaper");
		APP_PACKAGE_NAMES.add("com.android.vpndialogs");
		APP_PACKAGE_NAMES.add("com.mediatek.systemupdate.sysoper");
		APP_PACKAGE_NAMES.add("com.vivo.gallery");
		APP_PACKAGE_NAMES.add("com.kuihua.wxdk");
		APP_PACKAGE_NAMES.add("com.vivo.simpleclock");
		APP_PACKAGE_NAMES.add("com.google.android.talk");
		APP_PACKAGE_NAMES.add("com.vivo.simplemusic");
		APP_PACKAGE_NAMES.add("com.android.attachcamera");
		APP_PACKAGE_NAMES.add("com.android.email");
		APP_PACKAGE_NAMES.add("com.sina.weibo");
		APP_PACKAGE_NAMES.add("com.iqoo.ageingtest");
		APP_PACKAGE_NAMES.add("com.vivo.space");
		APP_PACKAGE_NAMES.add("com.android.notes");
		APP_PACKAGE_NAMES.add("com.android.phone");
		APP_PACKAGE_NAMES.add("com.android.shell");
		APP_PACKAGE_NAMES.add("com.vivo.fingerprint");
		APP_PACKAGE_NAMES.add("kvpioneer.safecenter");
		APP_PACKAGE_NAMES.add("com.android.providers.userdictionary");
		APP_PACKAGE_NAMES.add("com.vivo.minscreen");
		APP_PACKAGE_NAMES.add("com.android.location.fused");
		APP_PACKAGE_NAMES.add("com.maidrobot.activity");
		APP_PACKAGE_NAMES.add("com.android.systemui");
		APP_PACKAGE_NAMES.add("com.bbk.scene.tech");
		APP_PACKAGE_NAMES.add("com.sogou.appmall");
		APP_PACKAGE_NAMES.add("com.vivo.livewallpaper.coralsea");
		APP_PACKAGE_NAMES.add("com.amap.android.location");
		APP_PACKAGE_NAMES.add("com.mediatek.sensorhub.settings");
		APP_PACKAGE_NAMES.add("com.bbk.SuperPowerSave");
		APP_PACKAGE_NAMES.add("com.mediatek.systemupdate");
		APP_PACKAGE_NAMES.add("com.vivo.browser");
		APP_PACKAGE_NAMES.add("com.mediatek.mtklogger");
		APP_PACKAGE_NAMES.add("com.andreader.prein");
		APP_PACKAGE_NAMES.add("com.taobao.taobao");
		APP_PACKAGE_NAMES.add("com.vivo.motionrecognition");
		APP_PACKAGE_NAMES.add("com.android.skinfour");
		APP_PACKAGE_NAMES.add("com.hiapk.marketpho");
		APP_PACKAGE_NAMES.add("com.gsamlabs.bbm");
		APP_PACKAGE_NAMES.add("com.mediatek.apst.target");
		APP_PACKAGE_NAMES.add("com.android.bluetooth");
		APP_PACKAGE_NAMES.add("com.android.providers.contacts");
		APP_PACKAGE_NAMES.add("com.netease.cloudmusic");
		APP_PACKAGE_NAMES.add("com.android.captiveportallogin");
		APP_PACKAGE_NAMES.add("com.android.skinthree");
		APP_PACKAGE_NAMES.add("com.vivo.p2pservice");
		APP_PACKAGE_NAMES.add("com.chaozh.iReader");
		APP_PACKAGE_NAMES.add("com.qima.wxd");
		APP_PACKAGE_NAMES.add("cn.com.fetion");
		APP_PACKAGE_NAMES.add("com.achievo.vipshop");
		APP_PACKAGE_NAMES.add("com.android.bbksoundrecorder");
		APP_PACKAGE_NAMES.add("com.bbk.account");
	}

	public static Map<String, String> IOS_DEVICE_SYSTEMS = new HashMap<String, String>();
	static{
		/**
		IOS_DEVICE_SYSTEMS.put("iPod1,1", "iPod Touch 1G");
		IOS_DEVICE_SYSTEMS.put("iPod2,1", "iPod Touch 2G");
		IOS_DEVICE_SYSTEMS.put("iPod3,1", "iPod Touch 3G");
		IOS_DEVICE_SYSTEMS.put("iPod4,1", "iPod Touch 4G");
		IOS_DEVICE_SYSTEMS.put("iPod5,1", "iPod Touch 5G");

		IOS_DEVICE_SYSTEMS.put("iPhone1,1", "iPhone 1G");
		IOS_DEVICE_SYSTEMS.put("iPhone1,2", "iPhone 3G");
		IOS_DEVICE_SYSTEMS.put("iPhone2,1", "iPhone 3GS");
		IOS_DEVICE_SYSTEMS.put("iPhone3,1", "iPhone 4");
		IOS_DEVICE_SYSTEMS.put("iPhone3,3", "iPhone 4");
		IOS_DEVICE_SYSTEMS.put("iPhone4,1", "iPhone 4s");
		IOS_DEVICE_SYSTEMS.put("iPhone5,1", "iPhone 5");
		IOS_DEVICE_SYSTEMS.put("iPhone5,2", "iPhone 5");
		**/

		IOS_DEVICE_SYSTEMS.put("AppleTV2,1", "Apple TV 2");
		IOS_DEVICE_SYSTEMS.put("iPhone10,3", DEVICE_MODEL_NAME_IPHONEX);
		IOS_DEVICE_SYSTEMS.put("iPhone3,1", "iPhone 4");
		IOS_DEVICE_SYSTEMS.put("iPod2,1", "iPod Touch 2G");
		IOS_DEVICE_SYSTEMS.put("iPad1,1", "iPad");
		IOS_DEVICE_SYSTEMS.put("AppleTV5,3", "Apple TV 4");
		IOS_DEVICE_SYSTEMS.put("iPhone10,4", "iPhone 8");
		IOS_DEVICE_SYSTEMS.put("iPhone6,1", "iPhone 5s");
		IOS_DEVICE_SYSTEMS.put("iPhone3,3", "iPhone 4");
		IOS_DEVICE_SYSTEMS.put("iPhone6,2", "iPhone 5s");
		IOS_DEVICE_SYSTEMS.put("iPhone9,1", "iPhone 7");
		IOS_DEVICE_SYSTEMS.put("iPhone10,5", "iPhone 8 Plus");
		IOS_DEVICE_SYSTEMS.put("iPod3,1", "iPod Touch 3G");
		IOS_DEVICE_SYSTEMS.put("iPhone9,2", "iPhone 7 Plus");
		IOS_DEVICE_SYSTEMS.put("iPad2,1", "iPad 2");
		IOS_DEVICE_SYSTEMS.put("iPad2,2", "iPad 2");
		IOS_DEVICE_SYSTEMS.put("iPhone10,6", "iPhone X");
		IOS_DEVICE_SYSTEMS.put("iPhone9,3", "iPhone 7");
		IOS_DEVICE_SYSTEMS.put("iPad2,3", "iPad 2");
		IOS_DEVICE_SYSTEMS.put("iPad2,4", "iPad 2");
		IOS_DEVICE_SYSTEMS.put("iPad2,5", "iPad mini");
		IOS_DEVICE_SYSTEMS.put("iPhone9,4", "iPhone 7 Plus");
		IOS_DEVICE_SYSTEMS.put("iPad2,6", "iPad mini");
		IOS_DEVICE_SYSTEMS.put("iPad2,7", "iPad mini");
		IOS_DEVICE_SYSTEMS.put("iPhone1,1", "iPhone 1G");
		IOS_DEVICE_SYSTEMS.put("iPod4,1", "iPod Touch 4G");
		IOS_DEVICE_SYSTEMS.put("iPad3,1", "iPad 3");
		IOS_DEVICE_SYSTEMS.put("iPad3,2", "iPad 3");
		IOS_DEVICE_SYSTEMS.put("iPhone1,2", "iPhone 3G");
		IOS_DEVICE_SYSTEMS.put("iPad3,3", "iPad 3");
		IOS_DEVICE_SYSTEMS.put("iPhone4,1", "iPhone 4s");
		IOS_DEVICE_SYSTEMS.put("iPad3,4", "iPad 4");
		IOS_DEVICE_SYSTEMS.put("iPad3,5", "iPad 4");
		IOS_DEVICE_SYSTEMS.put("iPad3,6", "iPad 4");
		IOS_DEVICE_SYSTEMS.put("i386", "Simulator");
		IOS_DEVICE_SYSTEMS.put("iPhone7,1", "iPhone 6 Plus");
		IOS_DEVICE_SYSTEMS.put("iPod5,1", "iPod Touch 5G");
		IOS_DEVICE_SYSTEMS.put("iPhone7,2", "iPhone 6");
		IOS_DEVICE_SYSTEMS.put("iPad4,1", "iPad Air");
		IOS_DEVICE_SYSTEMS.put("iPad4,2", "iPad Air");
		IOS_DEVICE_SYSTEMS.put("iPad4,3", "iPad Air");
		IOS_DEVICE_SYSTEMS.put("iPad4,4", "iPad mini 2");
		IOS_DEVICE_SYSTEMS.put("iPad4,5", "iPad mini 2");
		IOS_DEVICE_SYSTEMS.put("iPad4,6", "iPad mini 2");
		IOS_DEVICE_SYSTEMS.put("iPad4,7", "iPad mini 3");
		IOS_DEVICE_SYSTEMS.put("iPad4,8", "iPad mini 3");
		IOS_DEVICE_SYSTEMS.put("iPad4,9", "iPad mini 3");
		IOS_DEVICE_SYSTEMS.put("iPad6,11", "iPad 5 (WiFi)");
		IOS_DEVICE_SYSTEMS.put("iPad6,12", "iPad 5 (Cellular)");
		IOS_DEVICE_SYSTEMS.put("AppleTV3,1", "Apple TV 3");
		IOS_DEVICE_SYSTEMS.put("iPad5,3", "iPad Air 2");
		IOS_DEVICE_SYSTEMS.put("iPad5,4", "iPad Air 2");
		IOS_DEVICE_SYSTEMS.put("iPhone2,1", "iPhone 3GS");
		IOS_DEVICE_SYSTEMS.put("AppleTV3,2", "Apple TV 3");
		IOS_DEVICE_SYSTEMS.put("iPhone5,1", "iPhone 5");
		IOS_DEVICE_SYSTEMS.put("x86_64", "Simulator");
		IOS_DEVICE_SYSTEMS.put("iPhone5,2", "iPhone 5");
		IOS_DEVICE_SYSTEMS.put("iPad6,3", "iPad Pro 9.7");
		IOS_DEVICE_SYSTEMS.put("iPhone8,1", "iPhone 6s");
		IOS_DEVICE_SYSTEMS.put("iPad6,4", "iPad Pro 9.7");
		IOS_DEVICE_SYSTEMS.put("iPhone5,3", "iPhone 5c");
		IOS_DEVICE_SYSTEMS.put("iPhone8,2", "iPhone 6s Plus");
		IOS_DEVICE_SYSTEMS.put("iPhone5,4", "iPhone 5c");
		IOS_DEVICE_SYSTEMS.put("iPad6,7", "iPad Pro 12.9");
		IOS_DEVICE_SYSTEMS.put("iPhone10,1", "iPhone 8");
		IOS_DEVICE_SYSTEMS.put("iPad6,8", "iPad Pro 12.9");
		IOS_DEVICE_SYSTEMS.put("iPad7,1", "iPad Pro 12.9 inch 2nd gen (WiFi)");
		IOS_DEVICE_SYSTEMS.put("iPod1,1", "iPod Touch 1G");
		IOS_DEVICE_SYSTEMS.put("iPhone8,4", "iPhone SE");
		IOS_DEVICE_SYSTEMS.put("iPad7,2", "iPad Pro 12.9 inch 2nd gen (Cellular)");
		IOS_DEVICE_SYSTEMS.put("iPad7,3", "iPad Pro 10.5 inch (WiFi)");
		IOS_DEVICE_SYSTEMS.put("iPhone10,2", "iPhone 8 Plus");
		IOS_DEVICE_SYSTEMS.put("iPad7,4", "iPad Pro 10.5 inch (Cellular)");
	}
}
